'use strict';
// The network itself lives in network-data.js so the map, the transfer
// planner, the line quiz and the records page share one source of truth.
const {lines: LINES, stations: STATIONS} = window.METRO_NETWORK;
const byId=Object.fromEntries(LINES.map(l=>[l.id,l]));
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=document.querySelector('#metro-map');
const tabs=document.querySelector('#line-tabs');
const panel=document.querySelector('#line-panel');
let selected='all',scale=1,offsetX=0,offsetY=0;
// Round each corner with a quadratic curve; diagram remains resolution-independent.
function roundedPath(points,radius=12){let d=`M ${points[0].join(' ')}`;for(let i=1;i<points.length;i++){const p=points[i],a=points[i-1],b=points[i+1];if(!b){d+=` L ${p.join(' ')}`;break;}const da=Math.hypot(a[0]-p[0],a[1]-p[1]),db=Math.hypot(b[0]-p[0],b[1]-p[1]);const r=Math.min(radius,da/2,db/2);if(!da||!db)continue;const before=[p[0]+(a[0]-p[0])*r/da,p[1]+(a[1]-p[1])*r/da],after=[p[0]+(b[0]-p[0])*r/db,p[1]+(b[1]-p[1])*r/db];d+=` L ${before.join(' ')} Q ${p.join(' ')} ${after.join(' ')}`;}return d;}
function badge(id){return `<span class="small-badge" style="--line-color:${byId[id].color}">${id}</span>`;}
function renderMap(){
 tabs.innerHTML=`<button class="line-tab" data-line="all" aria-pressed="true">全部线路</button>`+LINES.map(l=>`<button class="line-tab" data-line="${l.id}" aria-pressed="false" style="--line-color:${l.color}" aria-label="${l.id}号线"><span class="tab-swatch"></span>${l.id}</button>`).join('');
 svg.innerHTML=`<title>南京地铁主要站点导览图</title><desc>展示14条相连线路及主要站点，非等比例。完整站序可通过线路按钮查看。</desc><path d="M -40 460 Q 180 435 290 350 T 520 195 T 855 -60" fill="none" stroke="#e6eeea" stroke-width="64"/><path d="M -40 460 Q 180 435 290 350 T 520 195 T 855 -60" fill="none" stroke="#f7faf8" stroke-width="1.5"/><text x="263" y="336" transform="rotate(-37 263 336)" fill="#9aafa1" font-size="14" letter-spacing="10">长 江</text><text x="179" y="328" class="region-label">江北新区</text><text x="792" y="240" class="region-label">栖 霞</text><text x="845" y="775" class="region-label">江 宁</text><ellipse cx="675" cy="289" rx="34" ry="42" fill="#edf3ef"/><text x="680" y="295" fill="#a5b7aa" font-size="11" text-anchor="middle">玄武湖</text>`;
 const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.setAttribute('id','route-layer');svg.append(group);
 // Primary lines sit above the peripheral links at shared stations.
 for(const l of [...LINES].reverse()){group.insertAdjacentHTML('beforeend',`<g class="route-group" data-map-line="${l.id}" aria-label="${l.id}号线"><path class="route-hit" d="${roundedPath(l.points)}"/><path class="route-path" d="${roundedPath(l.points)}" stroke="${l.color}"/></g>`);}
 for(const s of STATIONS){const [name,x,y,ids,dx,dy,anchor='start']=s;svg.insertAdjacentHTML('beforeend',`<g class="station-group" data-station-name="${escapeHTML(name)}" data-lines="${ids.join(',')}" tabindex="0" role="button" aria-label="查看${escapeHTML(name)}站厕所和车站资料"><circle cx="${x}" cy="${y}" r="${ids.length>1?5.4:3.1}" class="${ids.length>1?'interchange-dot':'station-dot'}" ${ids.length===1?`stroke="${byId[ids[0]].color}"`:''}/><text x="${x+dx}" y="${y+dy}" class="station-label ${ids.some(id=>byId[id].from===name||byId[id].to===name)?'terminal-label':''}" text-anchor="${anchor}">${escapeHTML(name)}</text></g>`);}
 for(const l of LINES){const [x,y]=l.points[0];const w=l.id.length>1?29:23;const move=l.id==='S3'?[-1,37]:l.id==='S9'?[0,-39]:l.id==='S1'?[35,30]:l.id==='10'?[0,-43]:l.id==='7'?[50,0]:l.id==='2'?[-2,30]:[-1,-32];svg.insertAdjacentHTML('beforeend',`<g class="map-end-badge" data-map-line="${l.id}" transform="translate(${x+move[0]-w/2} ${y+move[1]-10})"><rect width="${w}" height="20" rx="4" fill="${l.color}"/><text x="${w/2}" y="14" text-anchor="middle">${l.id}</text></g>`);}
}
function renderPanel(){
 if(selected==='all'){panel.innerHTML=`<p class="panel-kicker">南京 · 线网导览</p><div class="overview-top"><div><h3 class="panel-title">每一程，<br>都是南京。</h3><p class="panel-intro">从城市中轴到山水之间，<br>把日常与远方连起来。</p></div><div class="overview-stats"><div><div class="overview-stat"><strong>14</strong><span>条</span></div><p class="stat-caption">导览图收录线路</p></div></div></div><div class="panel-rule"></div><p class="panel-label">从这些站，认识南京</p><div class="key-stations">${[['新街口',['1','2']],['南京南站',['1','3','S1','S3']],['鸡鸣寺',['3','4']],['夫子庙',['3','5']]].map(([n,ids])=>`<div class="key-station"><button type="button" class="key-station-button" data-station-name="${n}">${n}</button><div class="small-badges">${ids.map(badge).join('')}</div></div>`).join('')}</div><p class="panel-hint"><svg viewBox="0 0 18 18"><circle cx="9" cy="9" r="7"/><path d="M9 8v5m0-8v1"/></svg>点击顶部线路编号，查看完整站序与沿线介绍。</p>`;return;}
 const l=byId[selected],stations=l.stations.split('|');panel.style.setProperty('--selected-color',l.color);
 panel.innerHTML=`<p class="panel-kicker">LINE ${l.id} / 线路详情</p><span class="panel-line-badge">${l.id}</span><h3>${l.name}</h3><p class="line-summary">${l.intro}</p><div class="line-route-meta">${l.from} <span aria-hidden="true">—</span> ${l.to}<br><span>${stations.length} 座车站${l.id==='5'?' · 竹山路需出站换乘':''}</span></div><p class="panel-label">沿线站点</p><ol class="station-list">${stations.map(name=>{const mapped=STATIONS.find(s=>s[0]===name||s[0]===name.split('·')[0]);const others=mapped?mapped[3].filter(id=>id!==selected):[];return `<li class="${mapped?'map-station':''}"><span>${escapeHTML(name)}</span><span class="small-badges">${others.map(badge).join('')}</span></li>`;}).join('')}</ol>`;
 for(const item of panel.querySelectorAll('.station-list li')){const name=item.firstElementChild.textContent;const button=document.createElement('button');button.type='button';button.textContent=name;button.dataset.stationName=name;button.setAttribute('aria-label',`查看${name}站厕所和车站资料`);item.firstElementChild.replaceWith(button);}
 panel.scrollTop=0;
}
function selectLine(id){if(!byId[id]&&id!=='all')return;selected=id;for(const b of tabs.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.line===id));for(const g of svg.querySelectorAll('[data-map-line]'))g.style.opacity=id==='all'||g.dataset.mapLine===id?'1':'.12';for(const g of svg.querySelectorAll('.station-group'))g.style.opacity=id==='all'||g.dataset.lines.split(',').includes(id)?'1':'.14';renderPanel();}
renderMap();renderPanel();
tabs.addEventListener('click',e=>{const b=e.target.closest('button[data-line]');if(b)selectLine(b.dataset.line);});
svg.addEventListener('click',e=>{if(dragMoved)return;const station=e.target.closest('[data-station-name]');if(station){window.openStationInfo?.(station.dataset.stationName);return;}const g=e.target.closest('[data-map-line]');if(g)selectLine(g.dataset.mapLine);});
svg.addEventListener('keydown',e=>{const station=e.target.closest('[data-station-name]');if(station&&['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();window.openStationInfo?.(station.dataset.stationName);}});
panel.addEventListener('click',e=>{const button=e.target.closest('[data-station-name]');if(button)window.openStationInfo?.(button.dataset.stationName);});
function applyTransform(){svg.style.transform=`translate(${offsetX}px,${offsetY}px) scale(${scale})`;document.querySelector('#zoom-value').textContent=Math.round(scale*100)+'%';document.querySelector('#zoom-in').disabled=scale>=3;document.querySelector('#zoom-out').disabled=scale<=.75;}
function zoom(delta){scale=Math.max(.75,Math.min(3,Math.round((scale+delta)*100)/100));applyTransform();}
document.querySelector('#zoom-in').addEventListener('click',()=>zoom(.25));document.querySelector('#zoom-out').addEventListener('click',()=>zoom(-.25));document.querySelector('#reset-map').addEventListener('click',()=>{scale=1;offsetX=offsetY=0;applyTransform();});
const viewport=document.querySelector('#map-viewport');let drag=null,dragMoved=false,pinchDistance=0,pinchScale=1;const pointers=new Map();
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});viewport.setPointerCapture(e.pointerId);if(pointers.size===2){const p=[...pointers.values()];pinchDistance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);pinchScale=scale;drag=null;}else{drag={x:e.clientX,y:e.clientY,ox:offsetX,oy:offsetY,line:e.target.closest('[data-map-line]')?.dataset.mapLine,station:e.target.closest('[data-station-name]')?.dataset.stationName};dragMoved=false;}viewport.classList.add('dragging');});
viewport.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()];scale=Math.max(.75,Math.min(3,pinchScale*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/pinchDistance));dragMoved=true;applyTransform();}else if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)dragMoved=true;offsetX=drag.ox+dx;offsetY=drag.oy+dy;applyTransform();}});
function endPointer(e){if(e.type==='pointerup'&&!dragMoved){if(drag?.station)window.openStationInfo?.(drag.station);else if(drag?.line)selectLine(drag.line);}pointers.delete(e.pointerId);drag=null;viewport.classList.remove('dragging');}viewport.addEventListener('pointerup',endPointer);viewport.addEventListener('pointercancel',endPointer);
viewport.addEventListener('keydown',e=>{if(e.target.closest('button'))return;const moves={ArrowLeft:[35,0],ArrowRight:[-35,0],ArrowUp:[0,35],ArrowDown:[0,-35]};if(moves[e.key]){e.preventDefault();offsetX+=moves[e.key][0];offsetY+=moves[e.key][1];applyTransform();}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(.25);}else if(e.key==='-'){e.preventDefault();zoom(-.25);}else if(e.key==='0'){scale=1;offsetX=offsetY=0;applyTransform();}});
document.querySelector('#expand-map').addEventListener('click',async()=>{const shell=document.querySelector('.map-shell');try{if(document.fullscreenElement)await document.exitFullscreen();else if(shell.requestFullscreen)await shell.requestFullscreen();else{shell.classList.toggle('map-expanded');}}catch{shell.classList.toggle('map-expanded');}});
document.addEventListener('fullscreenchange',()=>document.querySelector('#expand-map').setAttribute('aria-label',document.fullscreenElement?'退出全屏':'全屏查看线路图'));
document.addEventListener('click',e=>{const b=e.target.closest('[data-explore-line]');if(b){selectLine(b.dataset.exploreLine);document.querySelector('#network').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}});
